<?php include_once('header_prod.php'); ?>
 
<!-- HEADER END -->



<!--=======content================================-->
				<div class="container">

					<div class="row">

					<!--<div class="col-md-4">
							<h2>Terms of use</h2>
							<p>Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. <br><br>Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. <br><br>Quisque nulla. Vestibulum libero nisl, porta vel, scele risque eget, malesuada at, neque. Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. </p>
						</div> -->
						<div class="col-md-12">
							 <!-- Title --> 
							<div class="title text-center">
								<h2>Privacy <span> Policy </span></h2>
							</div>
							
							  <!-- Description --> 
						<!--	<p class="desc">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod.</p> -->
							<div class="privacy-right">
								<p>DiscoverMyPet.in (“Discover My Pet)” business unit of Navitor Healthcare Pvt Ltd will only disclose your Personal Information in accordance with this Privacy Policy. If you decline to submit personal information to us, then we will unfortunately not be in a position to provide the Services to you. </p>

								<p>Any of your personal information which you provide when you use Discover My Pet.in in an unencrypted manner and/or to an open, public environment or forum including (without limitation) any blog, chat room, albums, community, classifieds or discussion board, is not confidential, does not constitute Personal Information, and is not subject to protection under Privacy Policy. <br><br>Since such public environments are accessible by third parties, it is possible that third parties may collect and collate and use such information for their own purposes. You should accordingly be careful when deciding to share any of your Personal Information in such public environments. <br> Discover My Pet is not liable to you or any third party for any damages that you or any third party may suffer howsoever arising from your disclosure of Personal Information in any public environment. Disclose your personal information in a public environment at your own risk. </p>

								<div class="desc">The Information Discover My Pet may collect</div>
								<ul>
									<li> <p> User-provided Information: When you register for, browse and use the Website, you may provide Discover My Pet "identity information" (such as your name, email address, address, home or mobile telephone number etc, Pet Birth Date.). You may also be able to add a picture of yourself. </p></li>
									<li> <p> If you decide to register through or otherwise grant access to a third party, social networking or authentication service that we may make available ("Authentication Service"), such as Facebook Connect or Google, Discover My Pet may also collect any such "identity information" that you have provided to the Authentication Service from the account you have with the Authentication Service. </p></li>
									<li> <p> Details of transactions by your Facebook friends and other Facebook users generated by you through our Service.</p> </li>
									<li> <p> If you choose to provide such information, during registration or otherwise, you are giving Discover My Pet the permission to use and store it consistent with this policy. Therefore, please understand that when you sign in with Discover My Pet, you are not anonymous to us. </p> </li>
								
								</ul>
								
								<div class="desc">IP Addresses and cookies</div> 
								<p> We may collect information about your computer, including where available your IP address, operating system and browser type, for system administration and to report aggregate information to our advertisers. We may also collect such information from your Facebook friends and other Facebook users who use the Service. This is statistical data about our users' browsing actions and patterns, and does not identify any individual.</p>
								<ul> <li> <p>Please note that our advertisers may also use cookies, over which we have no control. </p></li> </ul>
								
								<div class="desc">The Way Discover My Pet Uses Information </div>
								<ul> <li> <p>Discover My Pet uses the information that you provide or that we collect in order to establish and enhance our relationship with you. Discover My Pet generally uses the information you provide or that we collect to operate, maintain, enhance, and provide all of the features and services found on the Website. If you have given Discover My Pet consent, we may use your personally identifiable information to provide you with information about Discover My Pet's features, services and other offerings that may be of interest to you. We may also send information or offers to groups of users on behalf of other businesses. </p></li> </ul> 
								
								<div class="desc"> When Discover My Pet Discloses Information </div>
								<ul> 
									<li> <p> <strong>Social Networks: </strong> Discover My Pet will disclose your personal information if you have explicitly agreed we may do so. In particular, we will disclose personal information where you have elected to connect your account on our Website to a social network or other similar service (e.g., Facebook or Google), or have elected to have your activity on our Website published to a social network or other similar service (e.g., Facebook or Google). To control the information that you share, you should review and, if appropriate, modify your privacy settings on such services. </p> </li>
									<li> <p> <strong>Required by Law: </strong> Discover My Pet may also disclose user information if required to do so by law or in good-faith belief that such action is necessary to comply with state and other governing bodies. </p> </li>
									<li> <p> <strong> Merger or Acquisition: </strong> In the event that Discover My Pet is acquired by or merged with a third-party we reserve the right, in any of these circumstances, to transfer or assign the information that we have collected from users as part of such merger, acquisition, sale, or other change of control. </p> </li>
									<li> <p> <strong> Other Purposes: </strong> Discover My Pet also reserves the right to disclose user information that we believe, good faith, is appropriate or necessary to take precautions against liability; protect Discover My Pet from fraudulent, abusive, or unlawful uses; to investigate and defend ourselves against any third-party claims or allegations; to assist government enforcement agencies; to protect the security or integrity of the Website; or to protect the rights, property, or personal safety of Discover My Pet, our Users, or others. </p> </li>
									
								</ul>
								
								
								<div class="desc"> Contact Us </div>
								<p>If there are any questions regarding this privacy policy you may contact us using the information below: </p>
								
								<p>		304, AmitSamruddhiAppartment,
										Behind Wills Lifestyle, <br/>
										OppBalgandharv Theatre, <br/>
										JangliMaharaj Road <br/>
										Pune- 411005
								</p>
								
								
								<div class="title text-center">
									<h2>Pricing <span> Information </span></h2>
								</div>
								<p> While <strong> Discover My Pet. </strong>in strives to provide accurate product and pricing information, pricing or typographical errors may occur. <strong>Discover My Pet. </strong>in cannot confirm the price of a product until after you order. In the event that a product is listed at an incorrect price or with incorrect information due to an error in pricing or product information, <strong> Discover My Pet. </strong>in shall have the right, at our sole discretion, to refuse or cancel any orders placed for that product, unless the product has already been dispatched. In the event that an item is mis-priced, <strong>Discover My Pet.</strong>in may, at its discretion, either contact you for instructions or cancel your order and notify you of such cancellation. Unless the product ordered by you has been dispatched, your offer will not be deemed accepted and <strong>Discover My Pet.</strong>in will have the right to modify the price of the product and contact you for further instructions using the e-mail address provided by you during the time of registration, or cancel the order and notify you of such cancellation. In the event that <strong>Discover My Pet.</strong>in accepts your order the same shall be debited to your credit card account and duly notified to you by email that the payment has been processed. The payment may be processed prior to<strong> Discover My Pet.</strong>in dispatch of the product that you have ordered. If we have to cancel the order after we have processed the payment, the said amount will be reversed back to your credit card account. </p>

								
								
								<div class="title text-center">
									<h2>Shipping & Delivery <span> Policy for Products </span></h2>
								</div>
								
								<p>We ship only in India buyers, orders are shipped through registered domestic courier companies and /or speed post only. Orders are shipped within 10 working days or as per the delivery date agreed at the time of order confirmation and delivering of the shipment subject to Courier Company / post office norms. Navitor Healthcare Pvt Ltd (Discover My Pet.in) is not liable for any delay in delivery by the courier company / postal authorities and only guarantees to hand over the consignment to the courier company or postal authorities within 3 working days from the date of the order and payment or as per the delivery date agreed at the time of order confirmation. Delivery of all orders will be to registered address of the buyer as per the credit/debit card only at all times (Unless specified at the time of Order). Radox Trading & Marketing Pvt Ltd(Discover My Pet.in) is in no way responsible for any damage to the order while in transit to the buyer. </p>
								
								<p> Free Shipping on all orders above Rs. 500 *t&c applicable <br>
								Free shipping not applicable on select items <br>
								Rs. 99  applicable  for Cash On Delivery (COD) payment method. <br>
								Dear Customer: COD facility is available for Order Value under INR 3000/- </p>
								
								
								<div class="title text-center">
									<h2>Order <span> Cancellation  </span></h2>
								</div> 
								<p> All order cancellations will be handled as per our Standard Cancellation Policy </p>
								<div class="desc">  Cancellation by Discover My Pet.in:  </div>
								<p>Please note that there may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being canceled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is canceled or if additional information is required to accept your order. Cash payment mode orders will be cancelled for non-receipt of cash within 48 hours from the time of placing the order. Cheque payment mode orders will be cancelled if cheque is not deposited or intimation of the same is not given to us within 48 hours from the time of placing the order. </p>
								
								
								<div class="desc"> Cancellation by Customer: </div>
								<p> If you cancel your order before your product has shipped, we will refund the entire amount. If the cancellation is after your product has shipped, you can do one of the following: </P>
								<ul> <li> <p> If your product has shipped but has not yet been delivered, contact Customer Support and inform them of the same </p> </li>
								<li> <p> If you received the product,it will be eligible for replacement, only in cases where there are defects found with the product. </p> </li> 
								</ul>
								
								
								<div class="title text-center">
									<h2>Replacement <span>   </span></h2>
								</div> 
								<p> In order to get a defective item replaced, contact Care via Contact Us Page or call on +91 9011855666, within 15 days from the date of delivery. The defective product or part of the product will be recalled and a replacement will be shipped immediately. </p>
								
								<div class="title text-center">
									<h2>Refund and <span> Return </span></h2>
								</div>  
								<p>Definition: 'Return' is defined as the action of giving back the item purchased by the customer to the Seller/Discover  My Pet on the Discover My Pet website. Following situations may arise: </p>
								
								<ul> 
									<li> <p> Item was defective </p> </li> 
									<li> <p> Item was damaged in transit </p> </li> 
									<li> <p> Products was / were missing </p> </li> 
									<li> <p> Wrong item was received </p> </li> 
								</ul>
								
								<div class="desc">Return could also result in refund of money in some of the cases.</div>
								
								<p>We encourage the customer to review the listing before making the purchase decision. In case the customer orders a wrong item, Discover My Pet/seller shall not be entitled to anyreturn/refund. </p>
								<div class="desc">The following RULES apply to this Policy: </div>
								<ul> <li> <p> Certain consumableitemswill not be returned or refunded, the list of such items include in case the seal is found to be broken. The list of such items includes food, grooming products, supplements, dog apparel, beds, car seat covers etc.</p> </li>
								<li> <p>In case of damaged or any missing product the customer needs to raise the request within 24hours from the time of delivery. Once the customer has raised the request, he/she needs to provide a visual proof (an image) of the damaged product to Discover My Pet within 3 days from the time of delivery.</p> </li>
								<li> <p> All items to be returned must be unused and in their original condition with all original tags and packaging intact and should not be broken or tampered with.</p> </li>
								 <li> <p> In the event the Seller accepts the return request raised by the customer, customer will have to return the product and then the refund shall be credited to the customer’s account.</p> </li>
								 <li> <p> Refund will only be processed after a quality check of the product by experts of Discover My Pet. </p> </li>
								</ul>
								
								<br />	
								
								
								
						<!--		
								<p>Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pel lentesque sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula. Aliquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibulum sed ante. Donec sagittis euismod purus.<br><br><a href="mailto:discovermypet.com">discovermypet.com</a></p>  -->
						</div>
					</div>
				</div>
				</div>




<!-- FOOTER -->

	<?php include_once('footer.php'); ?>
 
<!-- FOOTER END -->		